name: 'Check Release PR'
description: 'Checks if the current PR is a release PR using GitHub API'
outputs:
  is_release_pr:
    description: 'True if this is a release PR, false otherwise'
    value: ${{ steps.check_pr.outputs.is_release_pr }}
runs:
  using: "composite"
  steps:
    - name: Check PR labels
      id: check_pr
      shell: bash
      run: |
        PR_LABELS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.labels[].name')
        if echo "$PR_LABELS" | grep -q "autorelease" || [[ "${{ github.event.action }}" == "opened" && "${{ github.head_ref }}" == *"release-please"* ]]; then
          echo "is_release_pr=true" >> $GITHUB_OUTPUT
        else
          echo "is_release_pr=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ github.token }}
