name: "linting"
on:
  workflow_call:
    secrets:
      PAT:
        required: true

permissions:
  pull-requests: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-release-pr
        id: check_release
      - uses: amannn/action-semantic-pull-request@v5
        if: steps.check_release.outputs.is_release_pr == 'false'
        with:
          types: |
            fix
            feat
            chore
          ignoreLabels: |
            autorelease
            dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-release-pr
        id: check_release
      - uses: deepakputhraya/action-branch-name@master
        if: steps.check_release.outputs.is_release_pr == 'false'
        with:
          regex: '^(feat|fix)\/[a-z0-9_-]+$'
          allowed_prefixes: 'feat,fix'
          ignore: main,develop
          min_length: 3
          max_length: 60

  run-tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: ./.github/actions/check-release-pr
        id: check_release
      - uses: terraform-linters/setup-tflint@v4
        if: steps.check_release.outputs.is_release_pr == 'false'
        name: Setup TFLint
        with:
          tflint_version: v0.47.0
      - run: tflint
        if: steps.check_release.outputs.is_release_pr == 'false'
      - uses: hashicorp/setup-terraform@v3
        if: steps.check_release.outputs.is_release_pr == 'false'
        with:
          terraform_wrapper: false
      - run: |
          terraform init
          terraform validate
          terraform fmt -check -recursive
        if: steps.check_release.outputs.is_release_pr == 'false'
        continue-on-error: false

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out called repo
        uses: actions/checkout@v4
        with:
          repository: aztfmods/terraform-azure-workflows
          path: called
          token: ${{ secrets.PAT }}
      - uses: ./.github/actions/check-release-pr
        id: check_release
      - uses: actions/setup-go@v5
        if: steps.check_release.outputs.is_release_pr == 'false'
        with:
          check-latest: true
      - run: go mod download
        if: steps.check_release.outputs.is_release_pr == 'false'
        working-directory: called/tests
      - name: check out caller repo
        if: steps.check_release.outputs.is_release_pr == 'false'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: caller
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - run: go test -v ./...
        if: steps.check_release.outputs.is_release_pr == 'false'
        working-directory: called/tests
        env:
          README_PATH: "${{ github.workspace }}/caller/README.md"
