name: release-please

on:
  workflow_call:
    inputs:
      default_branch:
        type: string
        description: 'The default branch for the release'
        required: false
        default: 'main'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v3
        with:
          release-type: terraform-module
          default-branch: ${{ inputs.default_branch }}
